export type Product = {
  id: string;
  name: string;
  seller: string;
  category: string;
  price: number;
  rating: number;
  sold: number;
  sizes: string[];
  image: string;
  rawImage: string;
  fitNote: string;
  length: "short" | "regular" | "long";
  fitScore: number;
  confidence: number;
  color: string;
  fabric: string;
  tags: string[];
  warnings: string[];
  styleSuggestions: string[];
};

export const categories = ["All", "Jackets", "Hoodies", "Dresses", "Blouses", "Coats"];

export const heightRanges = [
  "Under 150 cm",
  "150-160 cm",
  "160-170 cm",
  "170-180 cm",
  "Above 180 cm",
];

export const bodyTypes = ["Slim", "Average", "Athletic", "Curvy", "Plus Size"];

export const products: Product[] = [
  {
    id: "jk-yellow-track",
    name: "Yellow Zip Track Jacket",
    seller: "Titchi Thrift",
    category: "Jackets",
    price: 1790,
    rating: 4.8,
    sold: 65,
    sizes: ["S", "M", "L"],
    image: "/products/enhanced/yellow-track-jacket.webp",
    rawImage: "/products/yellow-track-jacket.png",
    fitNote: "High collar, slim waist, full zipper",
    length: "regular",
    fitScore: 88,
    confidence: 84,
    color: "Mustard yellow",
    fabric: "Track knit",
    tags: ["Vintage", "Sport", "Statement"],
    warnings: ["Check sleeve length if under 155 cm", "Fitted waist may feel snug over layers"],
    styleSuggestions: ["Straight denim", "White sneakers", "Black mini skirt"],
  },
  {
    id: "jk-red-track",
    name: "Red Vintage Track Jacket",
    seller: "Titchi Thrift",
    category: "Jackets",
    price: 1990,
    rating: 4.7,
    sold: 65,
    sizes: ["S", "M", "L"],
    image: "/products/enhanced/red-track-jacket.webp",
    rawImage: "/products/red-track-jacket.png",
    fitNote: "Fitted red zip jacket with sleeve stripes",
    length: "regular",
    fitScore: 86,
    confidence: 82,
    color: "Deep red",
    fabric: "Track jersey",
    tags: ["Vintage", "Zip", "Retro"],
    warnings: ["Slim waist shape", "Shoulder width matters for athletic builds"],
    styleSuggestions: ["Wide-leg jeans", "Black cargos", "Low-profile sneakers"],
  },
  {
    id: "hd-red-cropped",
    name: "Red Cropped Hoodie",
    seller: "Titchi Thrift",
    category: "Hoodies",
    price: 1490,
    rating: 4.6,
    sold: 41,
    sizes: ["XS", "S", "M"],
    image: "/products/enhanced/red-cropped-hoodie.webp",
    rawImage: "/products/red-cropped-hoodie.png",
    fitNote: "Cropped hoodie with front zip pocket",
    length: "short",
    fitScore: 81,
    confidence: 79,
    color: "Cherry red",
    fabric: "Soft fleece",
    tags: ["Cropped", "Hoodie", "Casual"],
    warnings: ["Will look shorter on taller users", "Best with high-waist bottoms"],
    styleSuggestions: ["High-waist denim", "Track pants", "Pleated mini skirt"],
  },
  {
    id: "hd-teal",
    name: "Teal Graphic Hoodie",
    seller: "Titchi Thrift",
    category: "Hoodies",
    price: 1590,
    rating: 4.5,
    sold: 54,
    sizes: ["S", "M", "L"],
    image: "/products/enhanced/teal-hoodie.webp",
    rawImage: "/products/teal-hoodie.png",
    fitNote: "Relaxed hoodie, large front graphic",
    length: "regular",
    fitScore: 83,
    confidence: 80,
    color: "Deep teal",
    fabric: "Heavy fleece",
    tags: ["Graphic", "Relaxed", "Daily"],
    warnings: ["Graphic placement should be preserved in AI preview", "Relaxed body may look oversized on slim builds"],
    styleSuggestions: ["Black joggers", "Loose denim", "White sneakers"],
  },
  {
    id: "hd-pink",
    name: "Pink Cropped Hoodie",
    seller: "Titchi Thrift",
    category: "Hoodies",
    price: 1490,
    rating: 4.4,
    sold: 39,
    sizes: ["XS", "S", "M"],
    image: "/products/enhanced/pink-cropped-hoodie.webp",
    rawImage: "/products/pink-cropped-hoodie.png",
    fitNote: "Short hoodie with broad sleeves",
    length: "short",
    fitScore: 80,
    confidence: 77,
    color: "Hot pink",
    fabric: "Velour fleece",
    tags: ["Cropped", "Soft", "Street"],
    warnings: ["Short body length", "Sleeves may bunch on shorter arms"],
    styleSuggestions: ["Light denim", "Cargo skirt", "Platform sneakers"],
  },
  {
    id: "hd-yellow",
    name: "Yellow Berkeley Hoodie",
    seller: "Titchi Thrift",
    category: "Hoodies",
    price: 1690,
    rating: 4.7,
    sold: 58,
    sizes: ["S", "M", "L"],
    image: "/products/enhanced/yellow-berkeley-hoodie.webp",
    rawImage: "/products/yellow-berkeley-hoodie.png",
    fitNote: "Cropped pullover hoodie with bold chest print",
    length: "short",
    fitScore: 84,
    confidence: 82,
    color: "Golden yellow",
    fabric: "Fleece",
    tags: ["Graphic", "Cropped", "Campus"],
    warnings: ["Chest print must stay readable", "Cropped hem changes with height"],
    styleSuggestions: ["Blue denim", "Black leggings", "Canvas sneakers"],
  },
  {
    id: "dr-black-sequin",
    name: "Black Sequin Feather Dress",
    seller: "Titchi Thrift",
    category: "Dresses",
    price: 3290,
    rating: 4.9,
    sold: 81,
    sizes: ["XS", "S", "M"],
    image: "/products/enhanced/black-sequin-dress.webp",
    rawImage: "/products/black-sequin-dress.png",
    fitNote: "Strapless sequin dress with feather hem",
    length: "regular",
    fitScore: 91,
    confidence: 86,
    color: "Black",
    fabric: "Sequins and feather trim",
    tags: ["Party", "Sequin", "Evening"],
    warnings: ["Strapless fit depends on bust/chest measurement", "Feather hem may sit higher on taller users"],
    styleSuggestions: ["Minimal heels", "Silver jewelry", "Small evening bag"],
  },
  {
    id: "ct-brown",
    name: "Brown Leather Long Coat",
    seller: "Titchi Thrift",
    category: "Coats",
    price: 3890,
    rating: 4.8,
    sold: 81,
    sizes: ["S", "M", "L"],
    image: "/products/enhanced/brown-leather-coat.webp",
    rawImage: "/products/brown-leather-coat.png",
    fitNote: "Structured coat with pockets and zipper",
    length: "long",
    fitScore: 87,
    confidence: 84,
    color: "Weathered brown",
    fabric: "Faux leather / suede finish",
    tags: ["Coat", "Structured", "Vintage"],
    warnings: ["Long length may overwhelm under 155 cm", "Shoulder structure needs accurate model pose"],
    styleSuggestions: ["Black boots", "Straight pants", "Fitted inner top"],
  },
  {
    id: "bl-grey",
    name: "Grey Ruffle Blouse",
    seller: "Titchi Thrift",
    category: "Blouses",
    price: 1390,
    rating: 4.6,
    sold: 81,
    sizes: ["XS", "S", "M", "L"],
    image: "/products/enhanced/grey-ruffle-blouse.webp",
    rawImage: "/products/grey-ruffle-blouse.png",
    fitNote: "Soft sheer blouse with ruffle front",
    length: "regular",
    fitScore: 85,
    confidence: 82,
    color: "Grey print",
    fabric: "Light sheer woven",
    tags: ["Blouse", "Ruffle", "Soft"],
    warnings: ["Sheer texture should not be flattened by AI", "Sleeve drape needs arm position"],
    styleSuggestions: ["Black cami", "Wide trousers", "Silver necklace"],
  },
  {
    id: "dr-brown-pattern",
    name: "Brown Pattern Mini Dress",
    seller: "Titchi Thrift",
    category: "Dresses",
    price: 2290,
    rating: 4.7,
    sold: 81,
    sizes: ["XS", "S", "M"],
    image: "/products/enhanced/brown-pattern-dress.webp",
    rawImage: "/products/brown-pattern-dress.png",
    fitNote: "V-neck patterned mini dress",
    length: "short",
    fitScore: 84,
    confidence: 81,
    color: "Brown mixed print",
    fabric: "Light woven",
    tags: ["Mini", "Pattern", "Evening"],
    warnings: ["Mini length varies strongly by height", "Pattern should align at waist in AI preview"],
    styleSuggestions: ["Tall boots", "Small shoulder bag", "Layered necklace"],
  },
];
